### PR TITLE
add new maintainer

### PR DESCRIPTION
**Pull request by rluria14**
Checklist
    * [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
    * [x] Bumped the build number (if the version is unchanged)
    * [x] Reset the build number to `0` (if the version changed)
    * [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
    * [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rluria14** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@rluria14, can you please send PRs with more time between them. Our CI infrastructure is getting slow because of the PRs

**Comment by jakirkham** [comment]
Also would skip bumping the build number and skip CI for these kind of changes where CI isn't relevant (adding a new maintainer)

**Comment by rluria14** [comment]
@isuruf @jakirkham sorry about that. my script has finished running.

**Pull request merged**
